# Python Exercise 110 - Reducing your program even further
# Add to the coin.py module created in the previous challenges, a function called summary(), which displays on the screen
# some information generated by the functions we already have in the module created so far.
from ex_modules.coins import summary

price = float(input("Enter a price: $"))
summary(price, 30, 15)
